version: "3.3"
name: "PyAEDT-MCP-Development"

services:
  pyaedtdev:
    restart: always
    shm_size: "2gb"
    container_name: "PyAEDT-Development"
    mem_reservation: 8g
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../:/home/pyaedt/pyaedt-mcp:cached
    entrypoint: /bin/bash -c "while sleep 10000; do :; done"
