name: CI/CD

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'  # Daily at 04:30 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  ON_CI: "true"
  MAIN_PYTHON_VERSION: "3.13"
  PACKAGE_NAME: "ansys-aedt-mcp"
  DOCUMENTATION_CNAME: "aedt-mcp.docs.pyansys.com"

jobs:

  # NOTE: We do not allow dependabot to trigger the CI/CD pipeline automatically.
  # This is to mitigate supply chain attacks, where a malicious dependency update
  # could execute arbitrary code in our build environment.
  # Dependabot PRs must be reviewed carefully and approved manually before
  # running the CI.
  block-dependabot:
    name: Block dependabot (on dependabot PR)
    runs-on: ubuntu-latest
    steps:
      - name: Exit if dependabot triggered the workflow # zizmor: ignore[bot-conditions] safe ignore because we exit if dependabot is triggering the action
        if: github.triggering_actor == 'dependabot[bot]'
        run: |
          echo "::warning::Dependabot is not allowed to trigger this workflow. Please review carefully the changes before running the workflow manually."
          exit 1


  # NOTE: We do not allow the pre-commit-ci bot to trigger the CI/CD pipeline
  # automatically on PR it creates.
  # This is to mitigate supply chain attacks, where a malicious dependency update
  # could execute arbitrary code in our build environment.
  # PRs opened by the pre-commit-ci bot must be reviewed carefully and approved
  # manually before running the CI.
  block-pre-commit-ci-bot-PR:
    name: Block pre-commit-ci bot (on pre-commit-ci bot PR only)
    runs-on: ubuntu-latest
    steps:
      - name: Exit if pre-commit-ci bot triggered the workflow # zizmor: ignore[bot-conditions] safe ignore because we exit if pre-commit-ci bot is triggering the action
        if: github.triggering_actor == 'pre-commit-ci[bot]' && github.event.pull_request.head.ref == 'pre-commit-ci-update-config'
        run: |
          echo "::warning::pre-commit-ci bot is not allowed to trigger this workflow. Please review carefully the changes before running the workflow manually."
          exit 1


  # NOTE: We do not allow pyansys-ci-bot to trigger the CI/CD pipeline automatically
  # on dependabot's and pre-commit-ci bot's PR. This is to mitigate supply chain attacks,
  # where a malicious dependency update could execute arbitrary code in our build environment.
  # Dependabot and pre-commit-ci bot PRs must be reviewed carefully and approved manually before
  # running the CI.
  block-pyansys-ci-bot:
    name: Block PyAnsys-CI-bot (on dependabot and pre-commit-ci bot PR)
    needs: [block-dependabot, block-pre-commit-ci-bot-PR]
    runs-on: ubuntu-latest
    steps:
      - name: Exit if pyansys-ci-bot triggered the workflow on dependabot's PR
        if: github.triggering_actor == 'pyansys-ci-bot' && startsWith(github.head_ref, 'dependabot')
        run: |
          echo "::warning::PyAnsys CI bot is not allowed to trigger this workflow in dependabot's PR. Please review carefully the changes before running the workflow manually."
          exit 1
      - name: Exit if pyansys-ci-bot triggered the workflow on pre-commit-ci bot's PR
        if: github.triggering_actor == 'pyansys-ci-bot' && github.event.pull_request.head.ref == 'pre-commit-ci-update-config'
        run: |
          echo "::warning::PyAnsys CI bot is not allowed to trigger this workflow in pre-commit-ci bot's PR. Please review carefully the changes before running the workflow manually."
          exit 1

  code-style:
    name: "Code style checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the code
    steps:
      - name: "Run PyAnsys code style checks"
        uses: ansys/actions/code-style@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}

  docs-style:
    name: "Documentation style checks"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the code
      checks: write # Needed for reviewdog to create check runs
    steps:
      - name: "Run Ansys documentation style checks"
        uses: ansys/actions/doc-style@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
            token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}

  pr-name:
    if: github.event_name == 'pull_request'
    name: "Check the name of the PR"
    permissions:
      contents: read # Needed to checkout the code
      pull-requests: read # Needed to read pull request title for checks
    runs-on: ubuntu-latest
    steps:
      - name: Check commit name
        uses: ansys/actions/check-pr-title@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  actions-security:
    name: "Actions security"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout and scan workflows
    steps:
      - uses: ansys/actions/check-actions-security@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          generate-summary: true
          token: ${{ secrets.GITHUB_TOKEN }}
          auditing-level: 'high'

  vulnerabilities:
    name: "Vulnerabilities"
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the code
      security-events: write # Needed to create security advisories
      issues: write # Needed to create issues for new advisories
    steps:
      - uses: ansys/actions/check-vulnerabilities@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          python-package-name: ${{ env.PACKAGE_NAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          dev-mode: ${{ github.ref != 'refs/heads/main' }}
          exit-with-error-on-new-advisory: false

  smoke-tests:
    name: "Build and smoke tests"
    runs-on: ${{ matrix.os }}
    needs: [code-style]
    permissions:
      contents: read # Needed to checkout the code
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - name: "Build wheelhouse and perform smoke test"
        uses: ansys/actions/build-wheelhouse@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          operating-system: ${{ matrix.os }}
          python-version: ${{ matrix.python-version }}
          whitelist-license-check: 'fpdf2'

  test:
    name: "Test Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    needs: [smoke-tests]
    permissions:
      contents: read # Needed to checkout the code
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: "Run unit tests"
        uses: ansys/actions/tests-pytest@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          python-version: ${{ matrix.python-version }}
          pytest-markers: '-m "not integration"'
          group-dependencies-name: test

  build-docs:
    name: "Build documentation"
    runs-on: ubuntu-latest
    needs: [docs-style]
    permissions:
      contents: read # Needed to checkout the code
    steps:
      - name: "Run Ansys documentation building action"
        uses: ansys/actions/doc-build@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          dependencies: 'zip libgl1 libglx-mesa0 xvfb'
          sphinxopts: '-W --keep-going'
          group-dependencies-name: doc

  package:
    name: "Package library"
    needs: [test, build-docs]
    runs-on: ubuntu-latest
    permissions:
      attestations: write # Required to upload provenance attestations
      contents: read # Needed to checkout the code
      id-token: write # Required for OIDC authentication to upload provenance attestations
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@d946b24b9a765f4169bcc94afdb27bd1a0533741 # v10.3.2
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          attest-provenance: false

  doc-deploy-dev:
    name: "Deploy development documentation"
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push documentation to gh-pages branch
    needs: [build-docs, package]
    steps:
      - name: "Deploy the latest documentation"
        uses: ansys/actions/doc-deploy-dev@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}

  doc-deploy-pr:
    name: "Deploy PR documentation"
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-preview')
    runs-on: ubuntu-latest
    needs: [build-docs]
    permissions:
      contents: write # Needed to push documentation to gh-pages branch
    steps:
      - name: "Deploy the PR documentation"
        uses: ansys/actions/doc-deploy-pr@d946b24b9a765f4169bcc94afdb27bd1a0533741 #v10.3.2
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
          bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
          bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
          maximum-pr-doc-deployments: 10
