name: Labeler

on:
  pull_request:
      types: [opened, reopened, synchronize, edited, labeled]
  push:
    branches: [ main ]
    paths:
      - '../labels.yml'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  label-syncer:
    name: Sync labels
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Required to read repository files and .github/labels.yml configuration
      pull-requests: write # Needed to add existing labels to PRs
      issues: write        # Needed to create labels that do not already exist
    steps:
    - name: Install Git and checkout project
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Sync labels with config from labels.yml
      uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  labeler:
    name: Set labels
    needs: label-syncer
    runs-on: ubuntu-latest
    permissions:
      contents: read       # Required to read repository files and .github/labeler.yml configuration
      pull-requests: write # Needed to add/modify labels on pull requests
    steps:
    - name: Install Git and checkout project
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Add label(s) to PR based on changed files or branch name
      uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  changelog-fragment:
    name: Create changelog fragment
    needs: labeler
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Required to commit changelog fragments to the repository
      pull-requests: write  # Required to update PR with changelog information
    steps:
    - uses: ansys/actions/doc-changelog@a5b0351dc277d68c2dc1beca2d2674c7dfa4fc55 # v10.3.3
      with:
        bot-email: ${{ secrets.PYANSYS_CI_BOT_EMAIL }}
        bot-user: ${{ secrets.PYANSYS_CI_BOT_USERNAME }}
        token: ${{ secrets.PYANSYS_CI_BOT_TOKEN }}
        use-pull-request-title: true
        use-default-towncrier-config: true
        use-python-cache: false
